rabbitmq:
  protocol: 'amqp'
  host: 'localhost'
  port: 5672
  user: 'user'
  password: 'BGNdWquZ'
  durable: true

mongodb:
  host: 'localhost'
  port: 27017
  user: 'user'
  password: 'BGNdWquZ'

logger_service:
  queue: 'logger'

mail_service:
  queue: 'mail'

user_service:
  queue: 'user'